targets:
  $default:
    builders:
      diver_flutter_builder|url_aggregator:
        enabled: true

builders:
  url_aggregator:
    import: "package:diver_flutter_builder/builder.dart"
    builder_factories: ["urlAggregatorBuilder"]
    build_extensions:
      $package$:
        - "diver/app_urls.json"
        - "diver/app_urls_errors.json"
    auto_apply: dependents
    build_to: source
    required_inputs:
      - ".dart"
