import 'package:flutter/material.dart';
import 'package:go_router/go_router.dart';

import 'routes.dart';

void main() => runApp(const ExampleApp());

class ExampleApp extends StatelessWidget {
  const ExampleApp({super.key});

  @override
  Widget build(BuildContext context) {
    // `$appRoutes` is generated by go_router_builder from the @TypedGoRoute
    // classes in routes.dart.
    final router = GoRouter(
      initialLocation: '/home',
      routes: $appRoutes,
    );
    return MaterialApp.router(
      title: 'diver_flutter_builder example',
      routerConfig: router,
    );
  }
}
